### ISSUE TITLE
Add code to repo

### ISSUE THREAD

**Issue by mathiasbolle** [grizlibier/wcomf#1]
Great job with writing your first game!

But sadly, the code is only available if i download the release.
Maybe you can add your code to this gh repo?

**Comment by doorfed** [comment]
Hello and sorry for taking so long! I had all the code in the repo before, but it grew a bit too much and updating it became a pain, so that's why all the code is in the releases.

**Comment by doorfed** [comment]
Hey there. No idea if you'll ever see this, but you were right. Not having the code out there is more of a pain and I was just stupid. I'll be restoring the codebase.
